### PR TITLE
fix(transducers): #186, Fix crash when using empty string as source for several transducers

### LINKED ISSUE #186: [transducers] Transducers crash when source is an empty string
Most transducers take a source sequence as a final argument.  Since strings are iterable, so you can do this:

```javascript
[...tx.filter(x => true, "abc")]
"abc"
```

However, if you provide an empty string, they will crash:

```javascript
[...tx.filter(x => true, "")]
TypeError: tx.filter(...) is not iterable
```

This is obviously because the transducer functions do a truthiness test on their final argument to determine whether a source was provided:

```typescript
export function map<A, B>(fn: Fn<A, B>): Transducer<A, B>;
export function map<A, B>(fn: Fn<A, B>, src: Iterable<A>): IterableIterator<B>;
export function map<A, B>(fn: Fn<A, B>, src?: Iterable<A>): any {
    return src
        ? iterator1(map(fn), src)
        : (rfn: Reducer<any, B>) => {
              const r = rfn[2];
              return compR(rfn, (acc, x: A) => r(acc, fn(x)));
          };
}
```

This could be corrected by replacing `src` with `isIterable(src)` (using `@thi.ng/checks`).  This would incur the additional work of looking up `Symbol.iterator`, but it would seem to be more correct.  I can't think of a case where this would be a breaking change (i.e. values for `src` that work now but are not iterable by that test).

@postspectacular  I'm willing to PR if you think this is actionable.  I understand there's a lot of branch work going on, so whatever you think best.

A workaround for the time being is to wrap the string argument in `[...s]`.

### PR DESCRIPTION
**Pull request by gavinpc-mindgrub**
Includes tests for _some_ of the affected transducers.

**NOTE**: This _changes the behavior_ of `flatten` when a string is passed as the source argument (per discussion in issue).

Fixes #186

### CODE REVIEW

File: packages/transducers/test/flatten.ts [hunk 1]
```diff
@@ -14,6 +14,11 @@ describe("flatten", () => {
     it("strings", () => {
         assert.deepEqual([...flatten(["", "a"])], ["", "a"]);
         assert.deepEqual([...flatten([[], ["a"], ""])], ["a", ""]);
+        assert.deepEqual([...flatten([["abc"]])], ["abc"]);
+        assert.deepEqual([...flatten(["abc"])], ["abc"]);
+        assert.deepEqual([...flatten("abc")], ["abc"]);
+        assert.deepEqual([...flatten([""])], [""]);
+        assert.deepEqual([...flatten("")], [""]);
```
Comment (gavinpc-mindgrub) [inline packages/transducers/test/flatten.ts:21]: This should be in a separate group saying "treats strings as atomic".  (I thought I had done that...)

**Comment by postspectacular** [comment]
OMG! Good things come to those who wait! :) Thank you so much for sticking with it - almost thought you moved on by now. Looks all good to me! 🙏 💯

File: packages/transducers/test/flatten.ts (hunk 1 above)
Comment (postspectacular) [reply packages/transducers/test/flatten.ts:21]: That's fine - will move those myself! Thank you!

**Comment by postspectacular** [comment]
@gavinpc-mindgrub in case you haven't seen it yet, released it all (plus some additional minor refactoring of other stuff) as v7.0.0

**Comment by gavinpc-mindgrub** [comment]
Thanks @postspectacular.  I finally straightened out my process so I am using umbrella as a submodule and can more easily test changes locally.  Have a few more things coming your way.

OT, but I am curious if there is a TL;DR about the hdom2020 work.  I am using hdom in a highly unusual way but I am wondering whether the approach is related.  I know... I should get in Discord :)  Just thought I'd ask in case you had an elevator pitch handy.

**Comment by postspectacular** [comment]
👍 Looking forward to see what's in the pipe... :)

As for hdom2020 - the elevator pitch is to more or less compile a hiccup tree ahead of time, avoid diffing as much as possible and embrace rstream subscriptions (embedded in the component tree) to drive DOM changes directly. The other important aspect is the overall component setup & lifecycle, e.g. mount/unmount lifecycle methods are async now and generally also allow for imperative updates. TL;DR hdom2020 is less centralized with more autonomy given to components in terms of internal/local state and how state changes are/should be updated/reflected... I will try to a more detailed write up soon. Still have more experimentation to do and build more proof-of-concept examples. But I already like it much more...
